### ISSUE TITLE
A bug about version 2.3.8

### ISSUE THREAD

**Issue by WinterLi1993** [dkoboldt/varscan#2]
Exception in thread "main" java.lang.NumberFormatException: For input string: "156051AAA>E;BBEEDDEEEEBEEEDEECEDE'@CD?CEEEEEE@DEDEEEEDEDEEEEE>C@FDE:EC6CEEEEFDEEECD/EBDEEEDDEEEEECADEDDDADDB"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at net.sf.varscan.Somatic.<init>(Somatic.java:1026)
	at net.sf.varscan.VarScan.somatic(VarScan.java:298)
	at net.sf.varscan.VarScan.main(VarScan.java:199)
HI ,I meet this error , what happened ???

thank you !

**Comment by dkoboldt** [comment]
Hello,

It looks like you have a malformed line in your mpileup file. Note: It’s HIGHLY recommended to use a two-sample mpileup (samtools mpileup -f reference.fa normal.bam tumor.bam) and run VarScan somatic with the --mpileup 1 flag, than to generate separate pileup files for normal and tumor. 

Yours,
Dan Koboldt





> On Oct 19, 2015, at 10:51 PM, DoubleWinter <notifications@github.com> wrote:
> 
> Exception in thread "main" java.lang.NumberFormatException: For input string: "156051AAA>E;BBEEDDEEEEBEEEDEECEDE'@CD <https://github.com/CD>?CEEEEEE@DEDEEEEDEDEEEEE>C@FDE:EC6CEEEEFDEEECD/EBDEEEDDEEEEECADEDDDADDB"
> at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> at java.lang.Integer.parseInt(Integer.java:492)
> at java.lang.Integer.parseInt(Integer.java:527)
> at net.sf.varscan.Somatic.(Somatic.java:1026)
> at net.sf.varscan.VarScan.somatic(VarScan.java:298)
> at net.sf.varscan.VarScan.main(VarScan.java:199)
> HI ,I meet this error , what happened ???
> 
> thank you !
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dkoboldt/varscan/issues/2>.
> 



____
This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by WinterLi1993** [comment]
Hi
 "  samtools mpileup  -l Resgion.bed  -f ref.fa  $normalBam $tumorBam | java -jar  VarScan.jar(2.3.8)  somatic --mpileup 1   --output-snp xxx.snp  --output-vcf  " , this command line is right ??
    I trying ...

**Comment by dkoboldt** [comment]
It looks right, though you should use "--output-vcf 1" to turn on that option.

**Comment by WinterLi1993** [comment]
yep ,it's work!thanks!
