### ISSUE TITLE
varscan copynumber running problem

### ISSUE THREAD

**Issue by jinxinhao0627** [dkoboldt/varscan#32]
Hi, 
I am running Varscan copynumber using the default settings. But met this error message.
Normal Pileup: normal.mpileup 
Tumor Pileup: tumor.mpileup 
Min coverage: 10 
Min avg qual: 15 
P-value thresh: 0.01 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5 
at net.sf.varscan.Copynumber.<init>(Copynumber.java:693) 
at net.sf.varscan.VarScan.copynumber(VarScan.java:328) 
at net.sf.varscan.VarScan.main(VarScan.java:209)

My command line is: java -jar ../../../software/VarScan.v2.3.9.jar copynumber normal.mpileup tumor.mpileup 007_008_glio 
I have no idea what has caused the problem.

Thank you in advance.

**Comment by sahirmohit** [comment]
remove the positions with zero depth.
awk '{if($4>0){print $0}}' normal.pileup >normal.nonzero.pileup
awk '{if($4>0){print $0}}' tumor.pileup >tumor.nonzero.pileup
java -jar VarScan.v2.3.9.jar copynumber normal.nonzero.pileup tumor.nonzero.pileup output_name
