### ISSUE TITLE
varscan somatic terminates without error, sometimes with an error

### ISSUE THREAD

**Issue by IanCodes** [dkoboldt/varscan#34]
When I run varscan somatic using a reference genome with a large number of contigs (>2000) the program completes without error, but does not output data in the outfile files for all the contigs.  All the contigs are present in the two mpileup files.

Sometimes I see a java error in the output:
---
Somatic p-value:        0.05
Warning:
java.lang.NullPointerException
        at net.sf.varscan.Somatic.comparePositions(Somatic.java:1669)
        at net.sf.varscan.Somatic.<init>(Somatic.java:1244)
        at net.sf.varscan.VarScan.somatic(VarScan.java:281)
        at net.sf.varscan.VarScan.main(VarScan.java:199)
16410533 positions in tumor
---

The maximum reported contigs appears to be ~170.

Thanks.

**Comment by hdetering** [comment]
I'm getting the exact same error, also only the header in the result.

As far as I was able to narrow it down it seems to happen in some cases when the tumor pileup has positions that don't occur in the normal.

Example:
```
$ cat tumor.pu | cut -f1 | uniq -c
  36964 1
    500 9
34874115 21
$ cat normal.pu | cut -f1 uniq -c
34878137 21
```
Running these two files returns the following error
```
$ java -jar VarScan.v2.4.3.jar somatic normal.pu tumor.pu tumor --output-vcf
Normal Pileup: normal.pu
Tumor Pileup: tumor.pu
NOTICE: While dual input files are still supported, using a single mpileup file (normal-tumor) with the --mpileup 1 setting is strongly recommended.
Min coverage:   8x for Normal, 6x for Tumor
Min reads2:     2
Min strands2:   1
Min var freq:   0.2
Min freq for hom:       0.75
Normal purity:  1.0
Tumor purity:   1.0
Min avg qual:   15
P-value thresh: 0.99
Somatic p-value:        0.05
Warning:
java.lang.NullPointerException
        at net.sf.varscan.Somatic.comparePositions(Somatic.java:1669)
        at net.sf.varscan.Somatic.<init>(Somatic.java:1244)
        at net.sf.varscan.VarScan.somatic(VarScan.java:281)
        at net.sf.varscan.VarScan.main(VarScan.java:199)
37465 positions in tumor
1 positions shared in normal
0 had sufficient coverage for comparison
0 were called Reference
0 were mixed SNP-indel calls and filtered
0 were called Germline
0 were called LOH
0 were called Somatic
0 were called Unknown
0 were called Variant
```
A **fix** that worked for me (since we only work with chromosome 21) is to exclude the positions beforehand that don't appear in the normal pileup.
